"""Lock/Unlock buttons for MyHOME actuators (WHO 14 "special" commands).

These entities are generated by `validate.py` only for devices that opted in with
`lock_buttons: true` AND whose WHERE is point-to-point, because `*14*0*0##` would
disable *every* actuator on the bus (plat-08).  The button device config is a copy of
the light/switch/cover entry with its own `entities` dict and a `source_platform`
key (Contract A, plat-09).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .gateway import MyHOMEGatewayHandler

from homeassistant.components.button import (
    DOMAIN as PLATFORM,
    ButtonEntity,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_MAC, CONF_NAME, EntityCategory
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from OWNd.message import OWNCommand

from .const import (
    CONF_BUS_INTERFACE,
    CONF_DEVICE_MODEL,
    CONF_ENTITY,
    CONF_MANUFACTURER,
    CONF_PLATFORMS,
    CONF_SOURCE_PLATFORM,
    CONF_WHERE,
    CONF_WHO,
    DOMAIN,
    LOGGER,
)
from .myhome_device import MyHOMEEntity
from .validate import is_point_to_point


async def async_setup_entry(
    hass: HomeAssistant,
    config_entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Create the Lock/Unlock buttons of this gateway (none when unconfigured)."""
    configured_buttons = hass.data[DOMAIN][config_entry.data[CONF_MAC]][CONF_PLATFORMS].get(PLATFORM, {})
    if not configured_buttons:
        return

    gateway_handler = hass.data[DOMAIN][config_entry.data[CONF_MAC]][CONF_ENTITY]
    buttons: list[MyHOMECommandButton] = []
    for device_id, cfg in configured_buttons.items():
        for entity_class in (DisableCommandButtonEntity, EnableCommandButtonEntity):
            buttons.append(
                entity_class(
                    hass=hass,
                    platform=PLATFORM,
                    device_id=device_id,
                    who=cfg[CONF_WHO],
                    where=cfg[CONF_WHERE],
                    interface=cfg.get(CONF_BUS_INTERFACE),
                    name=cfg[CONF_NAME],
                    source_platform=cfg.get(CONF_SOURCE_PLATFORM),
                    manufacturer=cfg[CONF_MANUFACTURER],
                    model=cfg[CONF_DEVICE_MODEL],
                    gateway=gateway_handler,
                )
            )

    async_add_entities(buttons)


def address_attributes(where: str, interface: str | None) -> dict[str, str]:
    """`A`/`PL` for point-to-point WHEREs, plain `Where` otherwise (plat-10)."""
    if is_point_to_point(where):
        attributes = {"A": where[: len(where) // 2], "PL": where[len(where) // 2 :]}
    else:
        attributes = {"Where": where}
    if interface is not None:
        attributes["Int"] = interface
    return attributes


class MyHOMECommandButton(MyHOMEEntity, ButtonEntity):
    """Base class of the two WHO 14 buttons attached to an actuator."""

    # Slot used to register the entity in `hass.data[...][entities]`: the base class
    # uses the platform name, but two buttons share one device dict.
    _registry_slot: str = "button"
    # WHO 14 WHAT: 0 disables (locks) the actuator, 1 enables (unlocks) it.
    _what: str = "0"
    _unique_id_suffix: str = ""

    def __init__(
        self,
        hass: HomeAssistant,
        platform: str,
        name: str,
        device_id: str,
        who: str,
        where: str,
        interface: str | None,
        source_platform: str | None,
        manufacturer: str | None,
        model: str | None,
        gateway: MyHOMEGatewayHandler,
    ) -> None:
        super().__init__(
            hass=hass,
            name=name,
            platform=platform,
            device_id=device_id,
            who=who,
            where=where,
            manufacturer=manufacturer,
            model=model,
            gateway=gateway,
        )

        # The base class pins `_attr_name = None` (the main entity of a device takes
        # the device name); these are secondary entities, so drop the attribute and
        # let `_attr_translation_key` provide the localised name (plat-16).
        del self._attr_name

        # Unique ids must stay exactly as `__init__.expected_unique_ids()` builds them.
        self._attr_unique_id = f"{gateway.mac}-{self._device_id}-{self._unique_id_suffix}"
        self._attr_entity_category = EntityCategory.CONFIG

        self._source_platform = source_platform
        self._interface = interface
        self._full_where = f"{self._where}#4#{self._interface}" if self._interface is not None else self._where

        self._attr_extra_state_attributes = address_attributes(where, self._interface)
        if source_platform is not None:
            self._attr_extra_state_attributes["Actuator"] = source_platform

    async def async_update(self) -> None:
        """Buttons have no state to poll (the base class calls this on add)."""

    async def async_added_to_hass(self) -> None:
        """Register under the button's own slot of the shared device dict."""
        await super().async_added_to_hass()
        entities = self._entities_registry()
        if entities is not None:
            # The base class registered us under the platform name; both buttons of a
            # device live in the same dict, so each takes its own slot.
            entities.pop(self._platform, None)
            entities[self._registry_slot] = self

    async def async_will_remove_from_hass(self) -> None:
        """Unregister the button."""
        entities = self._entities_registry()
        if entities is not None and entities.get(self._registry_slot) is self:
            del entities[self._registry_slot]
        await super().async_will_remove_from_hass()

    async def async_press(self) -> None:
        """Send the WHO 14 command as a parsed OWN message (never a raw string)."""
        frame = f"*14*{self._what}*{self._full_where}##"
        message = OWNCommand.parse(frame)
        if message is None:
            LOGGER.error("%s Refusing to send invalid command %s", self._gateway_handler.log_id, frame)
            return
        LOGGER.debug(
            "%s Sending %s for %s %s",
            self._gateway_handler.log_id,
            frame,
            self._source_platform or "device",
            self._device_id,
        )
        await self._gateway_handler.send(message)


class DisableCommandButtonEntity(MyHOMECommandButton):
    """Locks the actuator: it stops reacting to bus commands."""

    _attr_translation_key = "lock"
    _attr_icon = "mdi:lock-alert"
    _registry_slot = "disable"
    _unique_id_suffix = "disable"
    _what = "0"


class EnableCommandButtonEntity(MyHOMECommandButton):
    """Unlocks the actuator."""

    _attr_translation_key = "unlock"
    _attr_icon = "mdi:lock-open-variant-outline"
    _registry_slot = "enable"
    _unique_id_suffix = "enable"
    _what = "1"
