sync_time:
  fields:
    gateway:
      required: false
      example: "00:03:50:AA:BB:CC"
      selector:
        text:

send_message:
  fields:
    gateway:
      required: false
      example: "00:03:50:AA:BB:CC"
      selector:
        text:
    message:
      required: true
      example: "*1*0*0##"
      selector:
        text:

start_sending_instant_power:
  target:
    entity:
      integration: myhome
      domain: sensor
      device_class: power
  fields:
    duration:
      required: false
      example: 125
      selector:
        number:
          min: 1
          max: 255
          unit_of_measurement: min
          mode: box

start_discovery:
  fields:
    gateway:
      required: false
      example: "00:03:50:AA:BB:CC"
      selector:
        text:

stop_discovery:
  fields:
    gateway:
      required: false
      example: "00:03:50:AA:BB:CC"
      selector:
        text:

cover_calibration_run:
  target:
    entity:
      integration: myhome
      domain: cover
  fields:
    direction:
      required: true
      example: close
      selector:
        select:
          options:
            - close
            - open

cover_calibration_compute:
  target:
    entity:
      integration: myhome
      domain: cover
  fields:
    height:
      required: true
      example: 195
      selector:
        number:
          min: 1
          max: 500
          step: 0.5
          unit_of_measurement: cm
          mode: box
    closed_half_cm:
      required: true
      example: 59
      selector:
        number:
          min: 0
          max: 500
          step: 0.5
          unit_of_measurement: cm
          mode: box
    opened_half_cm:
      required: false
      example: 60
      selector:
        number:
          min: 0
          max: 500
          step: 0.5
          unit_of_measurement: cm
          mode: box
    slat_time:
      required: false
      example: 4.7
      selector:
        number:
          min: 0
          max: 60
          step: 0.1
          unit_of_measurement: s
          mode: box
