sync_time:
  fields:
    gateway:
      required: false
      example: "00:03:50:00:00:00"
      selector:
        text:

send_message:
  fields:
    gateway:
      required: false
      example: "00:03:50:00:00:00"
      selector:
        text:
    message:
      required: true
      example: "*1*0*0##"
      selector:
        text:

start_sending_instant_power:
  target:
    entity:
      integration: myhome
      domain: sensor
      device_class: power
  fields:
    duration:
      required: false
      example: 125
      selector:
        number:
          min: 1
          max: 255
          unit_of_measurement: min
          mode: box

start_discovery:
  fields:
    gateway:
      required: false
      example: "00:03:50:00:00:00"
      selector:
        text:

stop_discovery:
  fields:
    gateway:
      required: false
      example: "00:03:50:00:00:00"
      selector:
        text:
